# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(663, 207)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#avatarLabel {\n"
                           "    border-radius: 100px;\n"
                           "    \n"
                           "    border-image: url(:/imgs/avatar.jpg);\n"
                           "}")
        self.avatarLabel = QtWidgets.QLabel(Form)
        self.avatarLabel.setGeometry(QtCore.QRect(2, 2, 200, 200))
        self.avatarLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.avatarLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.avatarLabel.setText("")
        self.avatarLabel.setObjectName("avatarLabel")
        self.contentBrowser = QtWidgets.QTextBrowser(Form)
        self.contentBrowser.setGeometry(QtCore.QRect(201, 0, 462, 513))
        self.contentBrowser.setObjectName("contentBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Information"))
        self.contentBrowser.setHtml(_translate("Form",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
                                               "<h1 align=\"center\" style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"write\"></a><span style=\" font-size:8pt; font-weight:600;\">H</span><span style=\" font-size:8pt; font-weight:600;\">i 👋, I\'m MrSecond</span></h1>\n"
                                               "<h3 align=\"center\" style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">A passionate Coder from China</span></h3>\n"
                                               "<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:8pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🌱 <span style=\" font-weight:600;\">This software is design for the people who are troubled with environment variables in win10</span></li>\n"
                                               "<li style=\" font-size:8pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">📝 <span style=\" font-weight:600;\">Sofeware follows</span> <a href=\"http://en.wikipedia.org/wiki/MIT_License\"><span style=\" font-weight:600; text-decoration: underline; color:#0000ff;\">MIT License</span></a></li>\n"
                                               "<li style=\" font-size:8pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">📫 <span style=\" font-weight:600;\">Contact me with</span> <a href=\"mailto:lirichard520@gmail.com\"><span style=\" font-weight:600; text-decoration: underline; color:#0000ff;\">lirichard520@gmail.com</span></a></li></ul>\n"
                                               "<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


import icons_rc
